name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip python3-venv

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 使用最新的 Python 版本

    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt || echo "No requirements.txt file found, proceeding with pyinstaller only"

    - name: Build application
      run: |
        source venv/bin/activate
        pyinstaller --onefile JYp.py
      env:
        PYINSTALLER_ARCH: ${{ matrix.arch }}

    - name: Compress artifacts
      run: |
        cd dist
        tar -czf ../BySi_app_${{ matrix.arch }}.tar.gz *
      env:
        PYINSTALLER_ARCH: ${{ matrix.arch }}

    - name: List build artifacts
      run: ls -R dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: BySi_app_${{ matrix.arch }}
        path: BySi_app_${{ matrix.arch }}.tar.gz