name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, termux]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # 使用最新的 Python 版本

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt || echo "No requirements.txt file found, proceeding with pyinstaller only"
      if: matrix.arch != 'termux'

    - name: Build application for amd64 and arm64
      run: |
        source venv/bin/activate
        pyinstaller --onefile JYp.py
      if: matrix.arch != 'termux'

    - name: Install Termux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y proot qemu-user-static binfmt-support
        proot-distro install termux
        proot-distro login termux --shared-tmp --bind /dev --bind /sys --bind /proc -- apt-get update
        proot-distro login termux --shared-tmp --bind /dev --bind /sys --bind /proc -- apt-get install -y python python-pip python-venv
      if: matrix.arch == 'termux'

    - name: Build application for Termux
      run: |
        proot-distro login termux --shared-tmp --bind /dev --bind /sys --bind /proc -- python3 -m venv venv
        proot-distro login termux --shared-tmp --bind /dev --bind /sys --bind /proc -- venv/bin/pip install --upgrade pip
        proot-distro login termux --shared-tmp --bind /dev --bind /sys --bind /proc -- venv/bin/pip install pyinstaller
        proot-distro login termux --shared-tmp --bind /dev --bind /sys --bind /proc -- venv/bin/pip install -r requirements.txt || echo "No requirements.txt file found, proceeding with pyinstaller only"
        proot-distro login termux --shared-tmp --bind /dev --bind /sys --bind /proc -- pyinstaller --onefile JYp.py
      if: matrix.arch == 'termux'

    - name: Compress artifacts
      run: |
        cd dist
        tar -czf ../BySi_app_${{ matrix.arch }}.tar.gz *
      if: matrix.arch != 'termux'

    - name: List build artifacts
      run: ls -R dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: BySi_app_${{ matrix.arch }}
        path: BySi_app_${{ matrix.arch }}.tar.gz