name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 使用最新的 Python 版本

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt || echo "No requirements.txt file found, proceeding with pyinstaller only"

    - name: Generate requirements.txt
      run: |
        source venv/bin/activate
        pip freeze > requirements.txt

    - name: Build application
      run: |
        source venv/bin/activate
        pyinstaller --onefile JYp.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: flask-app
        path: dist/JYp

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false
        token: ${{ secrets.RELEASE_TOKEN }}

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/JYp
        asset_name: JYp
        asset_content_type: application/octet-stream
